### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by burakbinmunir**

### CODE REVIEW

**Review by shehryarmunir — APPROVED** [review]

**Review by shehryarmunir — CHANGES_REQUESTED** [review]
You need to add one more line

**Review by shehryarmunir — APPROVED** [review]

**Comment by shehryarmunir** [comment]
I have approved your pull request

**Review by shehryarmunir — CHANGES_REQUESTED** [review]
I am requesting some changes

**Comment by shehryarmunir** [comment]
I have requested some changes

**Review by shehryarmunir — CHANGES_REQUESTED** [review]
I am requesting some changes

**Comment by shehryarmunir** [comment]
I have requested some changes

**Review by shehryarmunir — CHANGES_REQUESTED** [review]
I am requesting some changes

**Comment by shehryarmunir** [comment]
I have requested some changes

**Review by shehryarmunir — APPROVED** [review]
I am approving the request

**Comment by shehryarmunir** [comment]
I have approved your request

**Review by shehryarmunir — CHANGES_REQUESTED** [review]
I am requesting some changes

**Comment by shehryarmunir** [comment]
I have requested some changes

**Review by shehryarmunir — APPROVED** [review]
I am approving the request

**Comment by shehryarmunir** [comment]
I have approved your request

**Comment by burakbinmunir** [comment]
aa

**Pull request merged**
